language: python
python:
# - "2.6"  # nose.tools.assert_greater_equal, ... do not exist
  - "2.7"
# - "3.3"  # too many to fix ...
  - "pypy"

# command to install dependencies
install:
  - "pip install ."
  - "python setup.py test"  # for installing `tests_require`
  - "pip install nose-cov"  # why `nose-cov` isn't correctlly installed by `setup.py test` ?

# command to run tests
script:
  - "python setup.py nosetests"

branches:
  only:
    - master
    - dev
