language: python
python:
  - "2.7"
  - "pypy"

# command to install dependencies
install:
  - "pip install ."
  - "python setup.py test"  # for installing `tests_require`

# command to run tests
script: python setup.py nosetests

branches:
  only:
    - master
    - dev
